# Generated by Django 5.2.1 on 2025-05-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('qr', 'Thanh toán QR Vietcombank')], max_length=20),
        ),
    ]
